image: gitpod/workspace-postgres

tasks:
  - init: npm install 
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev
    env:
      DATABASE_URL: postgres://./node_modules/.bin/prisma
  - command: npx prisma studio 
    env:
      DATABASE_URL: postgres://./node_modules/.bin/prisma
      
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432 
    onOpen: ignore
  - port: 5555 
    onOpen: open-browser
  
github:
  prebuilds:
    branches: true
    master: true
    pullRequests: true

vscode:
  extensions:
    - svelte.svelte-vscode
    - antfu.vite
    - prisma.prisma
