image: gitpod/workspace-postgres

tasks:
  - init: npm install 
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432 
    onOpen: ignore

github:
  prebuilds:
    branches: true
    master: true
    pullRequests: true

vscode:
  extensions:
    - svelte.svelte-vscode
    - antfu.vite
